-- 1. カテゴリテーブルの作成
create table if not exists categories (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  name text not null,
  color text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- カテゴリテーブルのRLS (Row Level Security) 設定
alter table categories enable row level security;

create policy "Users can view their own categories"
  on categories for select
  using ( auth.uid() = user_id );

create policy "Users can insert their own categories"
  on categories for insert
  with check ( auth.uid() = user_id );

-- 2. time_entries テーブルの更新 (title, category_id カラムの追加)
alter table time_entries 
add column if not exists title text,
add column if not exists category_id bigint references categories(id);
